### ISSUE TITLE
I can't use jupyter-tensorboard

### ISSUE THREAD

**Issue by MichaelJiangPlus** [lspvic/jupyter_tensorboard#14]
hello , i use jupyter hub to builad a cluster for myself,but i can't use temsorboard.
It show that :
1.Check that tensorflow(-gpu)>=1.3 is installed.
2.Check that jupyter, tensorflow and jupyter_tensorboard have the same python version.
3.Check that jupyter_tensorboard is installed via pip list. If you want uninstall this extension, run jupyter nbextension disable jupyter_tensorboard/tree --user and jupyter nbextension uninstall jupyter_tensorboard --user;
4.Copy your browser console logs to submit a new issue in https://github.com/lspvic/jupyter_tensorboard

After see this action , i start to check what is error .
my python version is 3.6.3
my tensorflow version is '1.5.0-rc1'

This is my pip list
PyQt5 (5.10.1)
PySocks (1.6.8)
python-dateutil (2.7.0)
python-editor (1.0.3)
python-Levenshtein (0.12.0)
python-oauth2 (1.0.1)
pytz (2018.3)
PyYAML (3.12)
pyzmq (17.0.0)
regex (2017.4.5)
requests (2.18.4)
requests-oauthlib (0.8.0)
rsa (3.4.2)
ruamel-yaml (0.15.35)
scikit-image (0.12.3)
scikit-learn (0.19.1)
scipy (1.0.0)
seaborn (0.7.1)
setuptools (39.0.1)
simplegeneric (0.8.1)
sip (4.19.8)
six (1.11.0)
sklearn (0.0)
sortedcontainers (1.5.9)
spacy (2.0.9)
SQLAlchemy (1.1.13)
statsmodels (0.8.0)
sympy (1.0)
tblib (1.3.2)
tensorflow-gpu (1.5.0rc1)
tensorflow-tensorboard (1.5.1)
termcolor (1.1.0)
terminado (0.8.1)
testpath (0.3.1)
textacy (0.6.0)
thinc (6.10.2)
toolz (0.9.0)
tornado (4.5.3)
tqdm (4.19.8)
traitlets (4.3.2)
ujson (1.35)
Unidecode (1.0.22)
urllib3 (1.22)
vincent (0.4.4)
wcwidth (0.1.7)
webencodings (0.5)
websocket-client (0.47.0)
Werkzeug (0.14.1)
wheel (0.30.0)
widgetsnbextension (2.0.1)
wrapt (1.10.11)
xlrd (1.1.0)
zict (0.1.3)

**Comment by MichaelJiangPlus** [comment]
after see what other issue i get some new error message 

```bash
jovyan@jupyter-bw022:~$ jupyter tensorboard enable --user
Enabling tree extension jupyter_tensorboard/tree...
      - Validating: OK
Enabling: jupyter_tensorboard
- Writing config: /home/jovyan/.jupyter
    - Validating...
      jupyter_tensorboard  OK
```

what can i see in my docker log:
```bash
[E 07:30:06.621 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 2898, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 38, in post
        .new_instance(data["logdir"], reload_interval=reload_interval)
      File "/opt/conda/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 104, in new_instance
        plugins = get_plugins()
      File "/opt/conda/lib/python3.6/site-packages/tensorboard/default.py", line 73, in get_plugins
        debugger = debugger_plugin_loader.get_debugger_plugin()
      File "/opt/conda/lib/python3.6/site-packages/tensorboard/plugins/debugger/debugger_plugin_loader.py", line 66, in get_debugger_plugin
        if FLAGS.debugger_data_server_grpc_port > 0 and FLAGS.debugger_port > 0:
      File "/opt/conda/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 488, in __getattr__
        raise _exceptions.UnparsedFlagAccessError(error_message)
    absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --debugger_data_server_grpc_port before flags were parsed.
[E 07:30:06.626 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "13",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8888",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|dd57f245|313589de79b79e2ff1a5ab4565ca7b26|1521611595",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en,zh;q=0.8,zh-CN;q=0.6",
      "Cookie": "_ga=GA1.1.972675684.1516243645; _xsrf=2|dd57f245|313589de79b79e2ff1a5ab4565ca7b26|1521611595; username-localhost-8888=\"2|1:0|10:1521617403|23:username-localhost-8888|44:OTQ5NGUxZTFjMGNhNGM4MzkzYzJiYTBmY2RlYWIzYTc=|94e41ca28854cd43f49eb5e4242047b4b67d37db244f9c14803ccf5d0af21b5a\""
    }
[E 07:30:06.627 NotebookApp] 500 POST /api/tensorboard (172.17.0.1) 6.64ms referer=http://localhost:8888/tree
```

**Comment by MichaelJiangPlus** [comment]
how can i fix this bug?

**Comment by lspvic** [comment]
What's your `jupyter-tensorboard` version? The error has occurred in old versions and I have fixed it.
You may upgrade your `jupyter-tensorboard` by 
`pip install -U jupyter-tensorboard`

**Comment by liudongqing** [comment]
I got lots of 404 error with latest docker :

`
[W 09:40:48.724 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 5.07ms referer=http://localhost:8888/tree/work/Untitled%20Folder
[W 09:40:48.740 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 4.88ms referer=http://localhost:8888/tree/work/Untitled%20Folder
[W 09:40:48.850 NotebookApp] 404 GET /api/tensorboard?_=1523958042724 (172.17.0.1) 3.21ms referer=http://localhost:8888/tree/work/Untitled%20Folder
[W 09:40:50.514 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 4.06ms referer=http://localhost:8888/tree/work
[W 09:40:50.562 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 11.49ms referer=http://localhost:8888/tree/work
[W 09:40:50.632 NotebookApp] 404 GET /api/tensorboard?_=1523958044550 (172.17.0.1) 3.69ms referer=http://localhost:8888/tree/work
[W 09:41:04.164 NotebookApp] 404 POST /api/tensorboard (172.17.0.1) 6.54ms referer=http://localhost:8888/tree/work
[W 09:41:30.278 NotebookApp] 404 POST /api/tensorboard (172.17.0.1) 3.21ms referer=http://localhost:8888/tree/work
[W 09:41:51.207 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 3.72ms referer=http://localhost:8888/tree/work
[W 09:41:51.253 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 11.05ms referer=http://localhost:8888/tree/work
[W 09:41:51.381 NotebookApp] 404 GET /api/tensorboard?_=1523958104936 (172.17.0.1) 2.76ms referer=http://localhost:8888/tree/work
[W 09:41:54.319 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 6.58ms referer=http://localhost:8888/tree/work
[W 09:41:54.334 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 4.92ms referer=http://localhost:8888/tree/work
[W 09:41:54.426 NotebookApp] 404 GET /api/tensorboard?_=1523958108207 (172.17.0.1) 2.15ms referer=http://localhost:8888/tree/work
[W 09:41:56.041 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 7.27ms referer=http://localhost:8888/tree/work/tflog
[W 09:41:56.063 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 6.82ms referer=http://localhost:8888/tree/work/tflog
[W 09:41:56.182 NotebookApp] 404 GET /api/tensorboard?_=1523958109970 (172.17.0.1) 3.09ms referer=http://localhost:8888/tree/work/tflog
[W 09:41:59.506 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 5.73ms referer=http://localhost:8888/tree/work
[W 09:41:59.539 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 10.83ms referer=http://localhost:8888/tree/work
[W 09:41:59.598 NotebookApp] 404 GET /api/tensorboard?_=1523958113471 (172.17.0.1) 3.25ms referer=http://localhost:8888/tree/work
[W 09:42:01.804 NotebookApp] 404 POST /api/tensorboard (172.17.0.1) 3.70ms referer=http://localhost:8888/tree/work
[W 09:42:12.767 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 4.44ms referer=http://localhost:8888/tree/work
[W 09:42:12.840 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 7.68ms referer=http://localhost:8888/tree/work
[W 09:42:12.941 NotebookApp] 404 GET /api/tensorboard?_=1523958126527 (172.17.0.1) 2.39ms referer=http://localhost:8888/tree/work
[I 09:43:05.712 NotebookApp] 302 GET / (172.17.0.1) 1.15ms
[W 09:43:06.655 NotebookApp] 404 GET /i18n/zh-CN/LC_MESSAGES/nbjs.json?v=20180417093930 (172.17.0.1) 9.12ms referer=http://localhost:8888/tree?
[W 09:43:06.670 NotebookApp] 404 GET /static/components/moment/locale/zh-cn.js?v=20180417093930 (172.17.0.1) 6.66ms referer=http://localhost:8888/tree?
[W 09:43:06.781 NotebookApp] 404 GET /api/tensorboard?_=1523958180223 (172.17.0.1) 1.84ms referer=http://localhost:8888/tree?
[W 09:43:09.066 NotebookApp] 404 POST /api/tensorboard (172.17.0.1) 3.53ms referer=http://localhost:8888/tree?
`

> spvic/tensorboard-notebook

   latest              b1460e640d70        2 months ago        4.99GB

**Comment by frankgu968** [comment]
I am experiencing the same issue. Did anyone come to a resolution for this?
