### ISSUE TITLE
How to run jupyter_tensorboard if I installed tensorflow in a virtualenv?

### ISSUE THREAD

**Issue by vkchan** [lspvic/jupyter_tensorboard#21]
I installed tensorflow in a virtualenv and I usually runs tensorflow in Jupyter Notebook through a kernel (which will invoke my virtualenv), could you please tell me how to configure `jupyter_tensorboard` so that it will invoke my virtualenv? Thanks!

```
$ jupyter notebook
[W 14:38:47.200 NotebookApp] Error loading server extension jupyter_tensorboard
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1481, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/ubuntu/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_tensorboard'

```

```
$ jupyter serverextension list
config dir: /home/ubuntu/.jupyter
    jupyter_tensorboard  enabled
    - Validating...
Error loading server extension jupyter_tensorboard
      X is jupyter_tensorboard importable?
config dir: /home/ubuntu/anaconda3/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 0.32.1 OK

```

**Comment by alexattia** [comment]
Same issue

**Comment by lspvic** [comment]
jupyter-tensorboard must be installed in ** the environment that jupyter notebook runs **. If jupyter is used in multiple environments, jupyter-tensorboard should be installed every environment.

**Comment by ghltshubh** [comment]
Same issue
