### ISSUE TITLE
Tensorboard 2.0 error

### ISSUE THREAD

**Issue by juliusvonkohout** [lspvic/jupyter_tensorboard#55]
Hello,

There is an incompatibility with tensorboard 2.0 which was just relased with tensorflow 2.0

Event Multiplexer initializing.
Event Multiplexer done initializing
Launching reload in a daemon thread
TensorBoard reload process beginning
Starting AddRunsFromDirectory: /opt/app-root/src/logs/fit
GetLogdirSubdirectories: Starting to list directories via walking.
Adding run from directory /opt/app-root/src/logs/fit/20191001-153636/validation
Constructing EventAccumulator for /opt/app-root/src/logs/fit/20191001-153636/validation
[E 15:48:17.963 LabApp] Uncaught exception POST /api/tensorboard?1569944897920 (127.0.0.1)
HTTPServerRequest(protocol='http', host='hostname', method='POST', uri='/api/tensorboard?1569944897920', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
result = method(*self.path_args, **self.path_kwargs)
File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 3174, in wrapper
return method(self, *args, **kwargs)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
.new_instance(data["logdir"], reload_interval=reload_interval)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 148, in new_instance
purge_orphaned_data=purge_orphaned_data)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 46, in create_tb_app
tensorboard.assets_zip_provider)
File "/opt/app-root/lib/python3.6/site-packages/tensorboard/backend/application.py", line 157, in standard_tensorboard_wsgi
flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 113, in TensorBoardWSGIApp
path_to_run = application.parse_event_files_spec(logdir)
File "/opt/app-root/lib/python3.6/site-packages/tensorboard/backend/application.py", line 455, in parse_event_files_spec
for specification in logdir_spec.split(','):
AttributeError: 'Namespace' object has no attribute 'split'
Adding run from directory /opt/app-root/src/logs/fit/20191001-153636/train
Constructing EventAccumulator for /opt/app-root/src/logs/fit/20191001-153636/train
...
[E 15:48:17.968 LabApp] 500 POST /api/tensorboard?1569944897920 (127.0.0.1) 19.22ms referer=https://hostname/lab?
POST /api/tensorboard?1569944897920 500 20.322 ms - 1529
Done with AddRunsFromDirectory: /opt/app-root/src/logs/fit

**Comment by alexandru-dinu** [comment]
Any updates on this?

**Comment by iFede94** [comment]
Tensorflow 2.0 supports the use of [Tensorboard directly inside Jupyter notebooks](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks) without the need of any additional library.

**Comment by juliusvonkohout** [comment]
> 
> 
> Tensorflow 2.0 supports the use of [Tensorboard directly inside Jupyter notebooks](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks) without the need of any additional library.

The problem is, that it does not work with jupyterhub. it just generates an iframe that does not work through a firewall.

**Comment by ZainRizvi** [comment]
+1 This also breaks support for GCP's AI Platform Notebooks, which relied on the jupyterlab_tensorboard plugin to allow people to access both the notebook and tensorboard on the same plugin

**Comment by chrisillapacloud** [comment]
Hi there, Many thanks for your great work!
Could you please update your docker hub image to Tensorflow 2.0 (and tensorboard 2.0)?

Thanks again!

**Comment by Luke035** [comment]
Same thing if I use it with tensorboard 2.0 within kubeflow notebook

**Comment by edoardogiacomello** [comment]
Even when launched inside a remote docker machine, the default supported solution would need to bind a new port in the remote host, which it's not always possible/preferable. 
The previous version also allowed Jupyter Lab to conveniently run (via a plugin) multiple instances of TB directly from the lab environment by just pressing a button. This would not be not so easy relying on the currently supported features.

**Comment by nfelt** [comment]
I believe https://github.com/lspvic/jupyter_tensorboard/commit/953375e9f6bb46510d6704b2bce04751d11108b7 was landed (PR #56) to address this, which is in the 0.2.0 release.

I'm not sure if that fully fixes it, but I would encourage folks to try that out.
