### ISSUE TITLE
TENSOR BOARD INSTALLED ERROR- PLEASE HELP

### ISSUE THREAD

**Issue by ntphuc01012019** [lspvic/jupyter_tensorboard#57]
E 20:07:54.135 NotebookApp] Uncaught exception POST /api/tensorboard (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='POST', uri='/api/tensorboard', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
        .new_instance(data["logdir"], reload_interval=reload_interval)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 148, in new_instance
        purge_orphaned_data=purge_orphaned_data)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 46, in create_tb_app
        tensorboard.assets_zip_provider)
      File "/opt/anaconda2/lib/python2.7/site-packages/tensorboard/backend/application.py", line 157, in standard_tensorboard_wsgi
        flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
      File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 113, in TensorBoardWSGIApp
        path_to_run = application.parse_event_files_spec(logdir)
      File "/opt/anaconda2/lib/python2.7/site-packages/tensorboard/backend/application.py", line 455, in parse_event_files_spec
        for specification in logdir_spec.split(','):
    AttributeError: 'Namespace' object has no attribute 'split'
[W 20:07:54.140 NotebookApp] Unhandled error
[E 20:07:54.141 NotebookApp] {
      "Origin": "http://localhost:8889", 
      "Content-Length": "25", 
      "Accept-Language": "de-de", 
      "Accept-Encoding": "gzip, deflate", 
      "X-Xsrftoken": "2|d20e9d1d|24b6990767e5b89db43360db8060fc08|1575033676", 
      "Host": "localhost:8889", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://localhost:8889/tree", 
      "Cookie": "username-localhost-8889=\"2|1:0|10:1575227270|23:username-localhost-8889|44:ZjNjYWJiOGZmMmVmNDNkYzhjM2ZkNDAzZGNiMzQ0NzQ=|d4f79e908efc494d5c2d1fd88b0962e5ccb3c2099898c03817b98f968724f8d2\"; username-localhost-8888=\"2|1:0|10:1575225899|23:username-localhost-8888|44:NjNiYjNmNjhjMGY3NDQ3YTk4ZDIyM2EzMjJiMjQwMDg=|d535aeb7b80df3c1324fb2dbdbd5c5d14ed3a5edc81c4350a3dc2628af32b01c\"; username-localhost-8890=\"2|1:0|10:1575133926|23:username-localhost-8890|44:MTRkNjcwYTgzYjlmNGViZGE2ZmZiZjdkNTBiNjc0YTg=|7e9ce04e08527ef047ef07c1815dfd948b86214d31bec804b2732275963f0aa7\"; _xsrf=2|d20e9d1d|24b6990767e5b89db43360db8060fc08|1575033676; username-localhost-8891=\"2|1:0|10:1573790658|23:username-localhost-8891|44:YzcwMWRhNTM1YzliNGI3NWJmNTE5OTI0ZWFmNGRkMzc=|ebb1d3e52cb510995a2eacd43a9f208eb9d0dfc3d21c925a78b2e5f51577a343\"", 
      "Content-Type": "application/json"
    }
[E 20:07:54.142 NotebookApp] 500 POST /api/tensorboard (::1) 34.74ms referer=http://localhost:8889/tree

**Comment by qrtt1** [comment]
you could try this 
https://github.com/lspvic/jupyter_tensorboard/pull/56
