### ISSUE TITLE
Extension error on launch

### ISSUE THREAD

**Issue by SpontaneousDuck** [lspvic/jupyter_tensorboard#66]
I am using my own jupyter notebook container and think I have installed everything as requested by the instructions for `jupyter_tensorboard`. When trying to open Tensorboard I get the extension error. My Chrome console shows the below error:
![image](https://user-images.githubusercontent.com/23267120/89433124-eda95400-d70f-11ea-8f95-2f657e044076.png)
The versions for relevant packages are shown below:
![image](https://user-images.githubusercontent.com/23267120/89433149-f732bc00-d70f-11ea-8791-4076e70cb75a.png)

Thanks for the help!

**Comment by rahulpshah** [comment]
Can you post the server logs from the jupyter server, it seems like the issue is related to tensorboard moving to 0.2.3.

**Comment by victor-moreno** [comment]
tensorboard 2.3.0 doesn't have application.standard_tensorboard_wsgi anymore:

[E 14:04:39.551 NotebookApp] 500 POST /api/tensorboard?1597493079364 (10.84.160.17) 117.26ms referer=http://z97mx.local:9996/lab
[E 14:07:23.942 NotebookApp] Uncaught exception POST /api/tensorboard?1597493243873 (10.84.160.17)
    HTTPServerRequest(protocol='http', host='z97mx.local:9996', method='POST', uri='/api/tensorboard?1597493243873', version='HTTP/1.1', remote_ip='10.84.160.17')
    Traceback (most recent call last):
      File "/packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/packages/tornado/web.py", line 3178, in wrapper
        return method(self, *args, **kwargs)
      File "/packages/jupyter_tensorboard/api_handlers.py", line 40, in post
        .new_instance(data["logdir"], reload_interval=reload_interval)
      File "/packages/jupyter_tensorboard/tensorboard_manager.py", line 223, in new_instance
        create_tb_app(
      File "/packages/jupyter_tensorboard/tensorboard_manager.py", line 45, in create_tb_app
        #            return application.standard_tensorboard_wsgi(
    AttributeError: module 'tensorboard.backend.application' has no attribute 'standard_tensorboard_wsgi'

The new function is application.TensorBoardWSGIApp but compatibility is uncertain. I have renamed the calls and the error disappears, but I still cannot manage to get it working in a docker container

**Comment by andreasfragner** [comment]
Same issue here. Doesn't seem entirely straight-forward to just replace `tensorboard.backend.application.standard_tensorboard_wsgi` with `TensorBoardWSGI`. Downgrading tensorboard may be an option but not sure which version that change happened in

**Comment by NanoCode012** [comment]
Hi @andreasfragner and those reading , I got this error when trying to use `jupyterlab_tensorboard` (frontend of this repo for jupyterlab) https://github.com/chaoleili/jupyterlab_tensorboard/issues/25#issue-684139674 . I fixed it by the following.

> Simple solution would be to tell users to `pip install tensorboard==2.2`.

**Comment by cliffwoolley** [comment]
If you want to use TB 2.3 or later, can you please try with https://github.com/lspvic/jupyter_tensorboard/pull/63 ?

**Comment by kuldip-barot** [comment]
Thanks @NanoCode012 `pip install tensorboard==2.2` solved my problem too.
