### ISSUE TITLE
Getting Jupyter tensorboard extension error when using TF 2.3.0

### ISSUE THREAD

**Issue by ebaranas** [lspvic/jupyter_tensorboard#69]
I'm building from this Dockerfile:

`FROM jupyter/tensorflow-notebook`
`RUN python -m pip install jupyter-tensorboard==0.2.0`

which uses TF 2.3.0. However, as soon as I create a tensorboard instance, I get this:

`AttributeError: module 'tensorboard.backend.application' has no attribute 'standard_tensorboard_wsgi'`

This does not happen when using TF <= 2.1.0.

**Comment by ikhoury** [comment]
Same issue currently happening in a fresh JupyterHub workspace with the latest TF:
```text
Nov 26 15:16:57 jupyter-test bash[31997]:     Traceback (most recent call last):
Nov 26 15:16:57 jupyter-test bash[31997]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/web.py", line 1590, in _execute
Nov 26 15:16:57 jupyter-test bash[31997]:         result = method(*self.path_args, **self.path_kwargs)
Nov 26 15:16:57 jupyter-test bash[31997]:       File "/opt/tljh/user/lib/python3.7/site-packages/tornado/web.py", line 3006, in wrapper
Nov 26 15:16:57 jupyter-test bash[31997]:         return method(self, *args, **kwargs)
Nov 26 15:16:57 jupyter-test bash[31997]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
Nov 26 15:16:57 jupyter-test bash[31997]:         .new_instance(data["logdir"], reload_interval=reload_interval)
Nov 26 15:16:57 jupyter-test bash[31997]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 221, in new_instance
Nov 26 15:16:57 jupyter-test bash[31997]:         purge_orphaned_data=purge_orphaned_data)
Nov 26 15:16:57 jupyter-test bash[31997]:       File "/opt/tljh/user/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 44, in create_tb_app
Nov 26 15:16:57 jupyter-test bash[31997]:         return application.standard_tensorboard_wsgi(
Nov 26 15:16:57 jupyter-test bash[31997]:     AttributeError: module 'tensorboard.backend.application' has no attribute 'standard_tensorboard_wsgi'
```

**Comment by drykovanov** [comment]
`standard_tensorboard_wsgi` was removed in 
https://github.com/tensorflow/tensorboard/commit/61df0809b16cc37a74cd1eebf9dd60163db17b04#diff-df834434b565cfafae02a1efaeed16893808d3b572c017a3b42ddece3e1c745c on May 19, 2020.

I believe latest working version is tensorboard 2.2.2.

**Comment by cliffwoolley** [comment]
If you want to use TB 2.3 or later, can you please try with https://github.com/lspvic/jupyter_tensorboard/pull/63 ?
