### ISSUE TITLE
Not working with TF 2.2.1

### ISSUE THREAD

**Issue by rvernaeshv** [lspvic/jupyter_tensorboard#72]
Hi...

I created a conda environment like this

```
conda create -n p38_jl2 --override-channels --strict-channel-priority -c conda-forge -c anaconda python=3.8.6 jupyterlab=2
```

Then installed `tensorflow==2.2.1` and `jupyter-tensorboard`.

And got this error running the TensorBoard Extension for a TensorFlow folder data:

```
Uncaught exception POST /api/tensorboard (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/tensorboard', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/rvernaes/miniconda3/envs/p38_jl2/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/rvernaes/miniconda3/envs/p38_jl2/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/home/rvernaes/miniconda3/envs/p38_jl2/lib/python3.8/site-packages/jupyter_tensorboard/api_handlers.py", line 39, in post
        self.settings["tensorboard_manager"]
      File "/home/rvernaes/miniconda3/envs/p38_jl2/lib/python3.8/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 219, in new_instance
        create_tb_app(
      File "/home/rvernaes/miniconda3/envs/p38_jl2/lib/python3.8/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 44, in create_tb_app
        return application.standard_tensorboard_wsgi(
      File "/home/rvernaes/miniconda3/envs/p38_jl2/lib/python3.8/site-packages/tensorboard/backend/application.py", line 146, in standard_tensorboard_wsgi
        return TensorBoardWSGIApp(
      File "/home/rvernaes/miniconda3/envs/p38_jl2/lib/python3.8/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 156, in TensorBoardWSGIApp_2x
        context = base_plugin.TBContext(
    TypeError: __init__() got an unexpected keyword argument 'db_connection_provider'
```

Already tried several combinations of TensorFlow versions without success.

Can somebody please instruct me which is the latest stable stack for this? (Python, TensorFlow, Jupyter Lab, etc?)

**Comment by rvernaeshv** [comment]
I could solve it by the following...

* Installed TensorFlow 2.4
* Build [this PR](https://github.com/cliffwoolley/jupyter_tensorboard/tree/tb-2.2-compat) locally, and install it.
* Ran
```
jupyter tensorboard enable --user
jupyter serverextension enable jupyter_tensorboard --user
jupyter nbextension enable jupyter_tensorboard/tree --user
```
* Installed `jupyterlab-tensorboard` extension
```
# For JupyterLab 2
jupyter labextension install jupyterlab_tensorboard
# For JupyterLab 3
pip install jupyterlab_tensorboard-0.2.1-py3-none-any.whl
```
