### ISSUE TITLE
tensorflow-tensorboard 1.5.0 released.

### ISSUE THREAD

**Issue by helmetti** [lspvic/jupyter_tensorboard#9]
### Tested environment
- python==3.6.4
- jupyter==1.0.0
- notebook==5.3.1
- tensorflow==1.5.0
- tensorflow-tensorboard==1.5.0 
- jupyter-tensorboard==0.1.4 
(I use Miniconda for reproducing the error, but Tensorflow is installed via pip)

### $ pip list |grep tensor
- jupyter-tensorboard (0.1.4)
- tensorflow (1.5.0)
- tensorflow-tensorboard (1.5.0)

I got the following error.
```
[E 09:52:59.725 NotebookApp] Uncaught exception POST /api/tensorboard (127.0.0.1)
    Traceback (most recent call last):
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/tornado/web.py", line 1510, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/notebook/base/handlers.py", line 670, in wrapper
        return method(self, *args, **kwargs)
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/tornado/web.py", line 2898, in wrapper
        return method(self, *args, **kwargs)
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 38, in post
        .new_instance(data["logdir"], reload_interval=reload_interval)
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 100, in new_instance
        plugins = get_plugins()
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/tensorboard/default.py", line 73, in get_plugins
        debugger = debugger_plugin_loader.get_debugger_plugin()
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/tensorboard/plugins/debugger/debugger_plugin_loader.py", line 66, in get_debugger_plugin
        if FLAGS.debugger_data_server_grpc_port > 0 and FLAGS.debugger_port > 0:
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
        wrapped(_sys.argv)
      File "/home/helmetti/miniconda3/envs/test/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
        name, value, suggestions=suggestions)
    absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'port'
```

**Comment by lspvic** [comment]
Thanks for your feedback.

Tensorboard [1.5.0](https://github.com/tensorflow/tensorboard/releases) tracks TensorFlow 1.5, so the versions should stay in sync. I think you can check your tensorflow version by `pip list |grep tensor`.

I have done some tests on tensorflow 1.5 (and also with tensorboard 1.5). After checking your tensorflow versions, If there are still errors, please let me know, thanks.

**Comment by helmetti** [comment]
Added environment. 
From python console, this worked.

`>>> from tensorboard import default
>>> plugins = get_plugins()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'get_plugins' is not defined
>>> get_plugins = default.get_plugins
>>> plugins = get_plugins()
`

**Comment by lspvic** [comment]
After some inspections, it seems that tensorflow-tensorboard (1.5.0) install package has some dependency problems, see https://github.com/tensorflow/tensorboard/pull/927 . They will release 1.5.1 soon, maybe it may resolve the problem.

Still, I cannot figure out why you got the above exceptions. It may be related with the dependent package `absl-py`. Can you run `pip check |grep tensorflow` to check your tensorflow or tensorboard dependency packages?

**Comment by lspvic** [comment]
I have found the reason and it is really a bug in tensorflow 1.5. I will fix it soon.
Many thanks you for your feedbacks.

**Comment by helmetti** [comment]
Confirmed it worked. 
Thank you so much, this saves my days!

-----
Just FYI
I got an error of missing font (looks like... Tensorboard is inheriting jupyter font setting)
```
[W 13:07:52.953 NotebookApp] 404 GET /font-roboto/RxZJdnzeo3R5zSexge8UUZBw1xU1rKptJj_0jans920.woff2 (127.0.0.1) 1.87ms referer=http://localhost:8080/tensorboard/1/
```
I think this is my environment problem of [jupyterthemes](https://github.com/dunovank/jupyter-themes).
(Tensorboard runs without any problem.)

**Comment by lspvic** [comment]
You are welcome. 

I also notice the font missing problem. It's due to the PR https://github.com/tensorflow/tensorboard/pull/751 from tensorboard 1.5, which uses absolute path for the font url. This extension cannot capture the absolute url from tensorboard. I will submit a PR to tensorboard. I will also try to solve the problem in my side.

**Comment by lspvic** [comment]
feel free to do sth. in github.

I think remain this issue open until solving the font missing problem. :blush:

**Comment by helmetti** [comment]
It's hard to say.... but I've got a different error on tensorflow-gpu 1.5.0. (GPU environment)

### Environment
- tensorflow-gpu==1.5.0
- tensorflow-tensorboard==1.5.0
- jupyter-tensorboard==0.1.5

```
[W 14:12:35.935 NotebookApp] Error loading server extension jupyter_tensorboard
    Traceback (most recent call last):
      File "/home/helmetti/miniconda3/envs/mycuda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1454, in init_server_extensions
        func(self)
      File "/home/helmetti/miniconda3/envs/mycuda/lib/python3.6/site-packages/jupyter_tensorboard/handlers.py", line 21, in load_jupyter_server_extension
        from .tensorboard_manager import manager
      File "/home/helmetti/miniconda3/envs/mycuda/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 17, in <module>
        from tensorboard import default
      File "/home/helmetti/miniconda3/envs/mycuda/lib/python3.6/site-packages/tensorboard/default.py", line 40, in <module>
        from tensorboard.plugins.debugger import debugger_plugin_loader
      File "/home/helmetti/miniconda3/envs/mycuda/lib/python3.6/site-packages/tensorboard/plugins/debugger/debugger_plugin_loader.py", line 26, in <module>
        tf.flags.DEFINE_integer(
    AttributeError: module 'tensorflow' has no attribute 'flags'
```
For quick reproducing by fresh environment, 
`pip install tensorflow-gpu` `pip install jupyter_tensorboard` causes
```
[I 14:35:05.186 NotebookApp] import tensorboard error, check tensorflow install
```

Tensorflow-gpu and Tensorflow environments are located at physically separated server.
So it's hard to think the CPU and GPU versions conflict....

If you have time please take a look.
(I believe your extension saves many data scientists.... To boot tensorboard from command line is really annoying...)

**Comment by lspvic** [comment]
Would you test your tensorflow and tensorboard in command line?
for example,
```
import tensorflow as tf
dir(tf)
```
```tensorboard --logdir=.```

**Comment by helmetti** [comment]
My bad. `tensorboard` doesn't boot.
`ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory`
Yes, I'd forgotten Tensorflow 1.5.0 requires CUDA9.0 from TF1.4.1 CUDA 8.0.
(I will prepare new CUDA server perhaps in next week...)

I will confirm 100 times before I post something, from next time.

**Comment by lspvic** [comment]
Never mind. 😄

**Comment by helmetti** [comment]
### Confirmed jupyter-tensorboard works on tensorflow GPU
- CUDA 9 / cuDNN 7
- tensorflow-gpu==1.5.0
- tensorflow-tensorboard==1.5.0
- jupyter-tensorboard==0.1.5

Still have a warning of missing font, but this is [tensorflow/tensorboard#751](https://github.com/tensorflow/tensorboard/pull/751) matter as you mentioned above. (I noticed you are using Chinese font, from users in CJK area might have another problem : I sometimes embed Japanese characters on tensorboard projector.) Anyhow, thanks for quick fixing. 👍

**Comment by helmetti** [comment]
Worked fine as tensorboard 1.5.1. Close this issue.
